name: continuous integration

on:
  pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: install dependencies
        run: pip install mkdocs
      - name: build
        run: mkdocs build